services:
  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    depends_on: [backend]
    ports:
      - "3000:3000"
    environment:
      # Stripe Secret Key
      - VITE_PUBLICATION_KEY=pk_test_51Ql8vKHzLwk0kDIFCLbEAuVY0wx0vZbVR9s1QgbfMoR7R80VVfKKA4g4tibGGESKQl53Gtzsx7SG2g9jyAHtuvt300Q7pJ3irf
      # Jitsi Key
      - VITE_JAAS_APP_ID=vpaas-magic-cookie-2cccc95a386147789d8d24341c6d2d9b
      # API Key for chatbot
      - VITE_API_KEY = 'AIzaSyDtjjoz5K6fNCjmNWp5HC8KuDdVUu3yDRE'

  backend:    
    build:
      context: backend
      dockerfile: Dockerfile  
      
    ports:
      - "5000:5000"  
    environment:
      # MongoDB URL
      - DBURL=mongodb://MongoUser:MongoPassword@MongoServer
      
      # NodeMailer
      - HOST_EMAIL=your_host_email
      - PASSWORD=your_app_password
      - PORT=587

      # Stripe
      - STRIPE_SECRET_KEY=your_stripe_secret_key

      # Backend server after deployment
      -  DOMAIN=your_domain

      # JWT Secret for encryption
      - SECRET=86d61b73-af1c-404c-ab30-f34464afc263

      # Notification
      - WHATSAPP=your_whatsapp_api_token
  
  models:
    build: 
      context: models
      dockerfile: Dockerfile
    ports:
      - "6000:6000"

        